// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// log_md
double log_md(double x);
RcppExport SEXP _ggflexbcr_log_md(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(log_md(x));
    return rcpp_result_gen;
END_RCPP
}
// phi_matrix_cpp
arma::mat phi_matrix_cpp(const arma::mat& X, const arma::vec& gamma1, const arma::vec& gamma2, const double& rho);
RcppExport SEXP _ggflexbcr_phi_matrix_cpp(SEXP XSEXP, SEXP gamma1SEXP, SEXP gamma2SEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gamma1(gamma1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gamma2(gamma2SEXP);
    Rcpp::traits::input_parameter< const double& >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(phi_matrix_cpp(X, gamma1, gamma2, rho));
    return rcpp_result_gen;
END_RCPP
}
// optimize_M1_phi
Rcpp::List optimize_M1_phi(const arma::mat& X, const arma::mat& Expc_k_given_C_mat, const arma::vec& censor_type_vec, arma::vec init_params, std::string method);
RcppExport SEXP _ggflexbcr_optimize_M1_phi(SEXP XSEXP, SEXP Expc_k_given_C_matSEXP, SEXP censor_type_vecSEXP, SEXP init_paramsSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Expc_k_given_C_mat(Expc_k_given_C_matSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type censor_type_vec(censor_type_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type init_params(init_paramsSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_M1_phi(X, Expc_k_given_C_mat, censor_type_vec, init_params, method));
    return rcpp_result_gen;
END_RCPP
}
// fmarginal_mc
double fmarginal_mc(double ti, arma::vec xi, arma::vec beta, double alpha, double q, double sigma, arma::vec mcs);
RcppExport SEXP _ggflexbcr_fmarginal_mc(SEXP tiSEXP, SEXP xiSEXP, SEXP betaSEXP, SEXP alphaSEXP, SEXP qSEXP, SEXP sigmaSEXP, SEXP mcsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type ti(tiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mcs(mcsSEXP);
    rcpp_result_gen = Rcpp::wrap(fmarginal_mc(ti, xi, beta, alpha, q, sigma, mcs));
    return rcpp_result_gen;
END_RCPP
}
// Smarginal_mc
double Smarginal_mc(double ti, arma::vec xi, arma::vec beta, double alpha, double q, double sigma, arma::vec mcs);
RcppExport SEXP _ggflexbcr_Smarginal_mc(SEXP tiSEXP, SEXP xiSEXP, SEXP betaSEXP, SEXP alphaSEXP, SEXP qSEXP, SEXP sigmaSEXP, SEXP mcsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type ti(tiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mcs(mcsSEXP);
    rcpp_result_gen = Rcpp::wrap(Smarginal_mc(ti, xi, beta, alpha, q, sigma, mcs));
    return rcpp_result_gen;
END_RCPP
}
// minus_S_t1_mc
double minus_S_t1_mc(double t1i, double t2i, arma::vec xi, arma::vec beta1, arma::vec beta2, double alpha1, double alpha2, double q, double sigma, arma::vec mcs);
RcppExport SEXP _ggflexbcr_minus_S_t1_mc(SEXP t1iSEXP, SEXP t2iSEXP, SEXP xiSEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP alpha1SEXP, SEXP alpha2SEXP, SEXP qSEXP, SEXP sigmaSEXP, SEXP mcsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t1i(t1iSEXP);
    Rcpp::traits::input_parameter< double >::type t2i(t2iSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha1(alpha1SEXP);
    Rcpp::traits::input_parameter< double >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mcs(mcsSEXP);
    rcpp_result_gen = Rcpp::wrap(minus_S_t1_mc(t1i, t2i, xi, beta1, beta2, alpha1, alpha2, q, sigma, mcs));
    return rcpp_result_gen;
END_RCPP
}
// S_mc
double S_mc(double t1i, double t2i, arma::vec xi, arma::vec beta1, arma::vec beta2, double alpha1, double alpha2, double q, double sigma, arma::vec mcs);
RcppExport SEXP _ggflexbcr_S_mc(SEXP t1iSEXP, SEXP t2iSEXP, SEXP xiSEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP alpha1SEXP, SEXP alpha2SEXP, SEXP qSEXP, SEXP sigmaSEXP, SEXP mcsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t1i(t1iSEXP);
    Rcpp::traits::input_parameter< double >::type t2i(t2iSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha1(alpha1SEXP);
    Rcpp::traits::input_parameter< double >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mcs(mcsSEXP);
    rcpp_result_gen = Rcpp::wrap(S_mc(t1i, t2i, xi, beta1, beta2, alpha1, alpha2, q, sigma, mcs));
    return rcpp_result_gen;
END_RCPP
}
// f_mc
double f_mc(double t1i, double t2i, arma::vec xi, arma::vec beta1, arma::vec beta2, double alpha1, double alpha2, double q, double sigma, arma::vec mcs);
RcppExport SEXP _ggflexbcr_f_mc(SEXP t1iSEXP, SEXP t2iSEXP, SEXP xiSEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP alpha1SEXP, SEXP alpha2SEXP, SEXP qSEXP, SEXP sigmaSEXP, SEXP mcsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t1i(t1iSEXP);
    Rcpp::traits::input_parameter< double >::type t2i(t2iSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha1(alpha1SEXP);
    Rcpp::traits::input_parameter< double >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mcs(mcsSEXP);
    rcpp_result_gen = Rcpp::wrap(f_mc(t1i, t2i, xi, beta1, beta2, alpha1, alpha2, q, sigma, mcs));
    return rcpp_result_gen;
END_RCPP
}
// Expc_k_given_C_mc
arma::mat Expc_k_given_C_mc(arma::vec t1, arma::vec t2, arma::mat X, arma::vec beta1, arma::vec beta2, double alpha1, double alpha2, double q, double sigma, arma::vec censor_type_vec, arma::vec phi11, arma::vec phi10, arma::vec phi01, arma::vec phi00, arma::vec mcs);
RcppExport SEXP _ggflexbcr_Expc_k_given_C_mc(SEXP t1SEXP, SEXP t2SEXP, SEXP XSEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP alpha1SEXP, SEXP alpha2SEXP, SEXP qSEXP, SEXP sigmaSEXP, SEXP censor_type_vecSEXP, SEXP phi11SEXP, SEXP phi10SEXP, SEXP phi01SEXP, SEXP phi00SEXP, SEXP mcsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha1(alpha1SEXP);
    Rcpp::traits::input_parameter< double >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censor_type_vec(censor_type_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi11(phi11SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi10(phi10SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi01(phi01SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi00(phi00SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mcs(mcsSEXP);
    rcpp_result_gen = Rcpp::wrap(Expc_k_given_C_mc(t1, t2, X, beta1, beta2, alpha1, alpha2, q, sigma, censor_type_vec, phi11, phi10, phi01, phi00, mcs));
    return rcpp_result_gen;
END_RCPP
}
// L_C2_matrix_mc
arma::mat L_C2_matrix_mc(arma::vec t1, arma::vec t2, arma::mat X, arma::vec beta1, arma::vec beta2, double alpha1, double alpha2, double q, double sigma, arma::vec censor_type_vec, arma::vec mcs);
RcppExport SEXP _ggflexbcr_L_C2_matrix_mc(SEXP t1SEXP, SEXP t2SEXP, SEXP XSEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP alpha1SEXP, SEXP alpha2SEXP, SEXP qSEXP, SEXP sigmaSEXP, SEXP censor_type_vecSEXP, SEXP mcsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha1(alpha1SEXP);
    Rcpp::traits::input_parameter< double >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censor_type_vec(censor_type_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mcs(mcsSEXP);
    rcpp_result_gen = Rcpp::wrap(L_C2_matrix_mc(t1, t2, X, beta1, beta2, alpha1, alpha2, q, sigma, censor_type_vec, mcs));
    return rcpp_result_gen;
END_RCPP
}
// Observed_ll_mc
double Observed_ll_mc(arma::vec gamma1, arma::vec gamma2, double rho, arma::vec beta1, arma::vec beta2, double alpha1, double alpha2, double q, double sigma, arma::vec t1, arma::vec t2, arma::mat X, arma::vec censor_type_vec, arma::vec mcs);
RcppExport SEXP _ggflexbcr_Observed_ll_mc(SEXP gamma1SEXP, SEXP gamma2SEXP, SEXP rhoSEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP alpha1SEXP, SEXP alpha2SEXP, SEXP qSEXP, SEXP sigmaSEXP, SEXP t1SEXP, SEXP t2SEXP, SEXP XSEXP, SEXP censor_type_vecSEXP, SEXP mcsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type gamma1(gamma1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma2(gamma2SEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha1(alpha1SEXP);
    Rcpp::traits::input_parameter< double >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censor_type_vec(censor_type_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mcs(mcsSEXP);
    rcpp_result_gen = Rcpp::wrap(Observed_ll_mc(gamma1, gamma2, rho, beta1, beta2, alpha1, alpha2, q, sigma, t1, t2, X, censor_type_vec, mcs));
    return rcpp_result_gen;
END_RCPP
}
// optimize_M2_lc2_q_fixed_mc
Rcpp::List optimize_M2_lc2_q_fixed_mc(arma::vec t1, arma::vec t2, arma::mat X, arma::mat Expc_k_given_C_mat, arma::vec censor_type_vec, double q, arma::vec mcs, arma::vec init_params, std::string method);
RcppExport SEXP _ggflexbcr_optimize_M2_lc2_q_fixed_mc(SEXP t1SEXP, SEXP t2SEXP, SEXP XSEXP, SEXP Expc_k_given_C_matSEXP, SEXP censor_type_vecSEXP, SEXP qSEXP, SEXP mcsSEXP, SEXP init_paramsSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Expc_k_given_C_mat(Expc_k_given_C_matSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censor_type_vec(censor_type_vecSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mcs(mcsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type init_params(init_paramsSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_M2_lc2_q_fixed_mc(t1, t2, X, Expc_k_given_C_mat, censor_type_vec, q, mcs, init_params, method));
    return rcpp_result_gen;
END_RCPP
}
// optimize_M2_lc2_gamma_mc
Rcpp::List optimize_M2_lc2_gamma_mc(arma::vec t1, arma::vec t2, arma::mat X, arma::mat Expc_k_given_C_mat, arma::vec censor_type_vec, double sigma, arma::vec mcs, arma::vec init_params, std::string method);
RcppExport SEXP _ggflexbcr_optimize_M2_lc2_gamma_mc(SEXP t1SEXP, SEXP t2SEXP, SEXP XSEXP, SEXP Expc_k_given_C_matSEXP, SEXP censor_type_vecSEXP, SEXP sigmaSEXP, SEXP mcsSEXP, SEXP init_paramsSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Expc_k_given_C_mat(Expc_k_given_C_matSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censor_type_vec(censor_type_vecSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mcs(mcsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type init_params(init_paramsSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_M2_lc2_gamma_mc(t1, t2, X, Expc_k_given_C_mat, censor_type_vec, sigma, mcs, init_params, method));
    return rcpp_result_gen;
END_RCPP
}
// optimize_M2_lc2_exp_mc
Rcpp::List optimize_M2_lc2_exp_mc(arma::vec t1, arma::vec t2, arma::mat X, arma::mat Expc_k_given_C_mat, arma::vec censor_type_vec, arma::vec mcs, arma::vec init_params, std::string method);
RcppExport SEXP _ggflexbcr_optimize_M2_lc2_exp_mc(SEXP t1SEXP, SEXP t2SEXP, SEXP XSEXP, SEXP Expc_k_given_C_matSEXP, SEXP censor_type_vecSEXP, SEXP mcsSEXP, SEXP init_paramsSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Expc_k_given_C_mat(Expc_k_given_C_matSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censor_type_vec(censor_type_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mcs(mcsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type init_params(init_paramsSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_M2_lc2_exp_mc(t1, t2, X, Expc_k_given_C_mat, censor_type_vec, mcs, init_params, method));
    return rcpp_result_gen;
END_RCPP
}
// fmarginal_cpp
double fmarginal_cpp(double ti, arma::vec xi, arma::vec beta, double alpha, double q, double sigma);
RcppExport SEXP _ggflexbcr_fmarginal_cpp(SEXP tiSEXP, SEXP xiSEXP, SEXP betaSEXP, SEXP alphaSEXP, SEXP qSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type ti(tiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(fmarginal_cpp(ti, xi, beta, alpha, q, sigma));
    return rcpp_result_gen;
END_RCPP
}
// Smarginal_cpp
double Smarginal_cpp(double ti, arma::vec xi, arma::vec beta, double alpha, double q, double sigma);
RcppExport SEXP _ggflexbcr_Smarginal_cpp(SEXP tiSEXP, SEXP xiSEXP, SEXP betaSEXP, SEXP alphaSEXP, SEXP qSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type ti(tiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(Smarginal_cpp(ti, xi, beta, alpha, q, sigma));
    return rcpp_result_gen;
END_RCPP
}
// minus_S_t1_cpp
double minus_S_t1_cpp(double t1i, double t2i, arma::vec xi, arma::vec beta1, arma::vec beta2, double alpha1, double alpha2, double q, double sigma);
RcppExport SEXP _ggflexbcr_minus_S_t1_cpp(SEXP t1iSEXP, SEXP t2iSEXP, SEXP xiSEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP alpha1SEXP, SEXP alpha2SEXP, SEXP qSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t1i(t1iSEXP);
    Rcpp::traits::input_parameter< double >::type t2i(t2iSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha1(alpha1SEXP);
    Rcpp::traits::input_parameter< double >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(minus_S_t1_cpp(t1i, t2i, xi, beta1, beta2, alpha1, alpha2, q, sigma));
    return rcpp_result_gen;
END_RCPP
}
// S_cpp
double S_cpp(double t1i, double t2i, arma::vec xi, arma::vec beta1, arma::vec beta2, double alpha1, double alpha2, double q, double sigma);
RcppExport SEXP _ggflexbcr_S_cpp(SEXP t1iSEXP, SEXP t2iSEXP, SEXP xiSEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP alpha1SEXP, SEXP alpha2SEXP, SEXP qSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t1i(t1iSEXP);
    Rcpp::traits::input_parameter< double >::type t2i(t2iSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha1(alpha1SEXP);
    Rcpp::traits::input_parameter< double >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(S_cpp(t1i, t2i, xi, beta1, beta2, alpha1, alpha2, q, sigma));
    return rcpp_result_gen;
END_RCPP
}
// f_cpp
double f_cpp(double t1i, double t2i, arma::vec xi, arma::vec beta1, arma::vec beta2, double alpha1, double alpha2, double q, double sigma);
RcppExport SEXP _ggflexbcr_f_cpp(SEXP t1iSEXP, SEXP t2iSEXP, SEXP xiSEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP alpha1SEXP, SEXP alpha2SEXP, SEXP qSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t1i(t1iSEXP);
    Rcpp::traits::input_parameter< double >::type t2i(t2iSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha1(alpha1SEXP);
    Rcpp::traits::input_parameter< double >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(f_cpp(t1i, t2i, xi, beta1, beta2, alpha1, alpha2, q, sigma));
    return rcpp_result_gen;
END_RCPP
}
// Expc_k_given_C_cpp
arma::mat Expc_k_given_C_cpp(arma::vec t1, arma::vec t2, arma::mat X, arma::vec beta1, arma::vec beta2, double alpha1, double alpha2, double q, double sigma, arma::vec censor_type_vec, arma::vec phi11, arma::vec phi10, arma::vec phi01, arma::vec phi00);
RcppExport SEXP _ggflexbcr_Expc_k_given_C_cpp(SEXP t1SEXP, SEXP t2SEXP, SEXP XSEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP alpha1SEXP, SEXP alpha2SEXP, SEXP qSEXP, SEXP sigmaSEXP, SEXP censor_type_vecSEXP, SEXP phi11SEXP, SEXP phi10SEXP, SEXP phi01SEXP, SEXP phi00SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha1(alpha1SEXP);
    Rcpp::traits::input_parameter< double >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censor_type_vec(censor_type_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi11(phi11SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi10(phi10SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi01(phi01SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi00(phi00SEXP);
    rcpp_result_gen = Rcpp::wrap(Expc_k_given_C_cpp(t1, t2, X, beta1, beta2, alpha1, alpha2, q, sigma, censor_type_vec, phi11, phi10, phi01, phi00));
    return rcpp_result_gen;
END_RCPP
}
// L_C2_matrix_cpp
arma::mat L_C2_matrix_cpp(arma::vec t1, arma::vec t2, arma::mat X, arma::vec beta1, arma::vec beta2, double alpha1, double alpha2, double q, double sigma, arma::vec censor_type_vec);
RcppExport SEXP _ggflexbcr_L_C2_matrix_cpp(SEXP t1SEXP, SEXP t2SEXP, SEXP XSEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP alpha1SEXP, SEXP alpha2SEXP, SEXP qSEXP, SEXP sigmaSEXP, SEXP censor_type_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha1(alpha1SEXP);
    Rcpp::traits::input_parameter< double >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censor_type_vec(censor_type_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(L_C2_matrix_cpp(t1, t2, X, beta1, beta2, alpha1, alpha2, q, sigma, censor_type_vec));
    return rcpp_result_gen;
END_RCPP
}
// Observed_ll_cpp
double Observed_ll_cpp(arma::vec gamma1, arma::vec gamma2, double rho, arma::vec beta1, arma::vec beta2, double alpha1, double alpha2, double q, double sigma, arma::vec t1, arma::vec t2, arma::mat X, arma::vec censor_type_vec);
RcppExport SEXP _ggflexbcr_Observed_ll_cpp(SEXP gamma1SEXP, SEXP gamma2SEXP, SEXP rhoSEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP alpha1SEXP, SEXP alpha2SEXP, SEXP qSEXP, SEXP sigmaSEXP, SEXP t1SEXP, SEXP t2SEXP, SEXP XSEXP, SEXP censor_type_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type gamma1(gamma1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma2(gamma2SEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha1(alpha1SEXP);
    Rcpp::traits::input_parameter< double >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censor_type_vec(censor_type_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(Observed_ll_cpp(gamma1, gamma2, rho, beta1, beta2, alpha1, alpha2, q, sigma, t1, t2, X, censor_type_vec));
    return rcpp_result_gen;
END_RCPP
}
// optimize_M2_lc2
Rcpp::List optimize_M2_lc2(arma::vec t1, arma::vec t2, arma::mat X, arma::mat Expc_k_given_C_mat, arma::vec censor_type_vec, arma::vec init_params, std::string method);
RcppExport SEXP _ggflexbcr_optimize_M2_lc2(SEXP t1SEXP, SEXP t2SEXP, SEXP XSEXP, SEXP Expc_k_given_C_matSEXP, SEXP censor_type_vecSEXP, SEXP init_paramsSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Expc_k_given_C_mat(Expc_k_given_C_matSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censor_type_vec(censor_type_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type init_params(init_paramsSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_M2_lc2(t1, t2, X, Expc_k_given_C_mat, censor_type_vec, init_params, method));
    return rcpp_result_gen;
END_RCPP
}
// optimize_M2_lc2_q_fixed
Rcpp::List optimize_M2_lc2_q_fixed(arma::vec t1, arma::vec t2, arma::mat X, arma::mat Expc_k_given_C_mat, arma::vec censor_type_vec, double q, arma::vec init_params, std::string method);
RcppExport SEXP _ggflexbcr_optimize_M2_lc2_q_fixed(SEXP t1SEXP, SEXP t2SEXP, SEXP XSEXP, SEXP Expc_k_given_C_matSEXP, SEXP censor_type_vecSEXP, SEXP qSEXP, SEXP init_paramsSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Expc_k_given_C_mat(Expc_k_given_C_matSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censor_type_vec(censor_type_vecSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type init_params(init_paramsSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_M2_lc2_q_fixed(t1, t2, X, Expc_k_given_C_mat, censor_type_vec, q, init_params, method));
    return rcpp_result_gen;
END_RCPP
}
// optimize_M2_lc2_gamma
Rcpp::List optimize_M2_lc2_gamma(arma::vec t1, arma::vec t2, arma::mat X, arma::mat Expc_k_given_C_mat, arma::vec censor_type_vec, arma::vec init_params, std::string method);
RcppExport SEXP _ggflexbcr_optimize_M2_lc2_gamma(SEXP t1SEXP, SEXP t2SEXP, SEXP XSEXP, SEXP Expc_k_given_C_matSEXP, SEXP censor_type_vecSEXP, SEXP init_paramsSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Expc_k_given_C_mat(Expc_k_given_C_matSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censor_type_vec(censor_type_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type init_params(init_paramsSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_M2_lc2_gamma(t1, t2, X, Expc_k_given_C_mat, censor_type_vec, init_params, method));
    return rcpp_result_gen;
END_RCPP
}
// optimize_M2_lc2_exp
Rcpp::List optimize_M2_lc2_exp(arma::vec t1, arma::vec t2, arma::mat X, arma::mat Expc_k_given_C_mat, arma::vec censor_type_vec, arma::vec init_params, std::string method);
RcppExport SEXP _ggflexbcr_optimize_M2_lc2_exp(SEXP t1SEXP, SEXP t2SEXP, SEXP XSEXP, SEXP Expc_k_given_C_matSEXP, SEXP censor_type_vecSEXP, SEXP init_paramsSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Expc_k_given_C_mat(Expc_k_given_C_matSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censor_type_vec(censor_type_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type init_params(init_paramsSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_M2_lc2_exp(t1, t2, X, Expc_k_given_C_mat, censor_type_vec, init_params, method));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ggflexbcr_log_md", (DL_FUNC) &_ggflexbcr_log_md, 1},
    {"_ggflexbcr_phi_matrix_cpp", (DL_FUNC) &_ggflexbcr_phi_matrix_cpp, 4},
    {"_ggflexbcr_optimize_M1_phi", (DL_FUNC) &_ggflexbcr_optimize_M1_phi, 5},
    {"_ggflexbcr_fmarginal_mc", (DL_FUNC) &_ggflexbcr_fmarginal_mc, 7},
    {"_ggflexbcr_Smarginal_mc", (DL_FUNC) &_ggflexbcr_Smarginal_mc, 7},
    {"_ggflexbcr_minus_S_t1_mc", (DL_FUNC) &_ggflexbcr_minus_S_t1_mc, 10},
    {"_ggflexbcr_S_mc", (DL_FUNC) &_ggflexbcr_S_mc, 10},
    {"_ggflexbcr_f_mc", (DL_FUNC) &_ggflexbcr_f_mc, 10},
    {"_ggflexbcr_Expc_k_given_C_mc", (DL_FUNC) &_ggflexbcr_Expc_k_given_C_mc, 15},
    {"_ggflexbcr_L_C2_matrix_mc", (DL_FUNC) &_ggflexbcr_L_C2_matrix_mc, 11},
    {"_ggflexbcr_Observed_ll_mc", (DL_FUNC) &_ggflexbcr_Observed_ll_mc, 14},
    {"_ggflexbcr_optimize_M2_lc2_q_fixed_mc", (DL_FUNC) &_ggflexbcr_optimize_M2_lc2_q_fixed_mc, 9},
    {"_ggflexbcr_optimize_M2_lc2_gamma_mc", (DL_FUNC) &_ggflexbcr_optimize_M2_lc2_gamma_mc, 9},
    {"_ggflexbcr_optimize_M2_lc2_exp_mc", (DL_FUNC) &_ggflexbcr_optimize_M2_lc2_exp_mc, 8},
    {"_ggflexbcr_fmarginal_cpp", (DL_FUNC) &_ggflexbcr_fmarginal_cpp, 6},
    {"_ggflexbcr_Smarginal_cpp", (DL_FUNC) &_ggflexbcr_Smarginal_cpp, 6},
    {"_ggflexbcr_minus_S_t1_cpp", (DL_FUNC) &_ggflexbcr_minus_S_t1_cpp, 9},
    {"_ggflexbcr_S_cpp", (DL_FUNC) &_ggflexbcr_S_cpp, 9},
    {"_ggflexbcr_f_cpp", (DL_FUNC) &_ggflexbcr_f_cpp, 9},
    {"_ggflexbcr_Expc_k_given_C_cpp", (DL_FUNC) &_ggflexbcr_Expc_k_given_C_cpp, 14},
    {"_ggflexbcr_L_C2_matrix_cpp", (DL_FUNC) &_ggflexbcr_L_C2_matrix_cpp, 10},
    {"_ggflexbcr_Observed_ll_cpp", (DL_FUNC) &_ggflexbcr_Observed_ll_cpp, 13},
    {"_ggflexbcr_optimize_M2_lc2", (DL_FUNC) &_ggflexbcr_optimize_M2_lc2, 7},
    {"_ggflexbcr_optimize_M2_lc2_q_fixed", (DL_FUNC) &_ggflexbcr_optimize_M2_lc2_q_fixed, 8},
    {"_ggflexbcr_optimize_M2_lc2_gamma", (DL_FUNC) &_ggflexbcr_optimize_M2_lc2_gamma, 7},
    {"_ggflexbcr_optimize_M2_lc2_exp", (DL_FUNC) &_ggflexbcr_optimize_M2_lc2_exp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_ggflexbcr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
