# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_md <- function(x) {
    .Call(`_ggflexbcr_log_md`, x)
}

phi_matrix_cpp <- function(X, gamma1, gamma2, rho) {
    .Call(`_ggflexbcr_phi_matrix_cpp`, X, gamma1, gamma2, rho)
}

optimize_M1_phi <- function(X, Expc_k_given_C_mat, censor_type_vec, init_params, method = "Nelder-Mead") {
    .Call(`_ggflexbcr_optimize_M1_phi`, X, Expc_k_given_C_mat, censor_type_vec, init_params, method)
}

fmarginal_mc <- function(ti, xi, beta, alpha, q, sigma, mcs) {
    .Call(`_ggflexbcr_fmarginal_mc`, ti, xi, beta, alpha, q, sigma, mcs)
}

Smarginal_mc <- function(ti, xi, beta, alpha, q, sigma, mcs) {
    .Call(`_ggflexbcr_Smarginal_mc`, ti, xi, beta, alpha, q, sigma, mcs)
}

minus_S_t1_mc <- function(t1i, t2i, xi, beta1, beta2, alpha1, alpha2, q, sigma, mcs) {
    .Call(`_ggflexbcr_minus_S_t1_mc`, t1i, t2i, xi, beta1, beta2, alpha1, alpha2, q, sigma, mcs)
}

S_mc <- function(t1i, t2i, xi, beta1, beta2, alpha1, alpha2, q, sigma, mcs) {
    .Call(`_ggflexbcr_S_mc`, t1i, t2i, xi, beta1, beta2, alpha1, alpha2, q, sigma, mcs)
}

f_mc <- function(t1i, t2i, xi, beta1, beta2, alpha1, alpha2, q, sigma, mcs) {
    .Call(`_ggflexbcr_f_mc`, t1i, t2i, xi, beta1, beta2, alpha1, alpha2, q, sigma, mcs)
}

Expc_k_given_C_mc <- function(t1, t2, X, beta1, beta2, alpha1, alpha2, q, sigma, censor_type_vec, phi11, phi10, phi01, phi00, mcs) {
    .Call(`_ggflexbcr_Expc_k_given_C_mc`, t1, t2, X, beta1, beta2, alpha1, alpha2, q, sigma, censor_type_vec, phi11, phi10, phi01, phi00, mcs)
}

L_C2_matrix_mc <- function(t1, t2, X, beta1, beta2, alpha1, alpha2, q, sigma, censor_type_vec, mcs) {
    .Call(`_ggflexbcr_L_C2_matrix_mc`, t1, t2, X, beta1, beta2, alpha1, alpha2, q, sigma, censor_type_vec, mcs)
}

Observed_ll_mc <- function(gamma1, gamma2, rho, beta1, beta2, alpha1, alpha2, q, sigma, t1, t2, X, censor_type_vec, mcs) {
    .Call(`_ggflexbcr_Observed_ll_mc`, gamma1, gamma2, rho, beta1, beta2, alpha1, alpha2, q, sigma, t1, t2, X, censor_type_vec, mcs)
}

optimize_M2_lc2_q_fixed_mc <- function(t1, t2, X, Expc_k_given_C_mat, censor_type_vec, q, mcs, init_params, method = "Nelder-Mead") {
    .Call(`_ggflexbcr_optimize_M2_lc2_q_fixed_mc`, t1, t2, X, Expc_k_given_C_mat, censor_type_vec, q, mcs, init_params, method)
}

optimize_M2_lc2_gamma_mc <- function(t1, t2, X, Expc_k_given_C_mat, censor_type_vec, sigma, mcs, init_params, method = "Nelder-Mead") {
    .Call(`_ggflexbcr_optimize_M2_lc2_gamma_mc`, t1, t2, X, Expc_k_given_C_mat, censor_type_vec, sigma, mcs, init_params, method)
}

optimize_M2_lc2_exp_mc <- function(t1, t2, X, Expc_k_given_C_mat, censor_type_vec, mcs, init_params, method = "Nelder-Mead") {
    .Call(`_ggflexbcr_optimize_M2_lc2_exp_mc`, t1, t2, X, Expc_k_given_C_mat, censor_type_vec, mcs, init_params, method)
}

fmarginal_cpp <- function(ti, xi, beta, alpha, q, sigma) {
    .Call(`_ggflexbcr_fmarginal_cpp`, ti, xi, beta, alpha, q, sigma)
}

Smarginal_cpp <- function(ti, xi, beta, alpha, q, sigma) {
    .Call(`_ggflexbcr_Smarginal_cpp`, ti, xi, beta, alpha, q, sigma)
}

minus_S_t1_cpp <- function(t1i, t2i, xi, beta1, beta2, alpha1, alpha2, q, sigma) {
    .Call(`_ggflexbcr_minus_S_t1_cpp`, t1i, t2i, xi, beta1, beta2, alpha1, alpha2, q, sigma)
}

S_cpp <- function(t1i, t2i, xi, beta1, beta2, alpha1, alpha2, q, sigma) {
    .Call(`_ggflexbcr_S_cpp`, t1i, t2i, xi, beta1, beta2, alpha1, alpha2, q, sigma)
}

f_cpp <- function(t1i, t2i, xi, beta1, beta2, alpha1, alpha2, q, sigma) {
    .Call(`_ggflexbcr_f_cpp`, t1i, t2i, xi, beta1, beta2, alpha1, alpha2, q, sigma)
}

Expc_k_given_C_cpp <- function(t1, t2, X, beta1, beta2, alpha1, alpha2, q, sigma, censor_type_vec, phi11, phi10, phi01, phi00) {
    .Call(`_ggflexbcr_Expc_k_given_C_cpp`, t1, t2, X, beta1, beta2, alpha1, alpha2, q, sigma, censor_type_vec, phi11, phi10, phi01, phi00)
}

L_C2_matrix_cpp <- function(t1, t2, X, beta1, beta2, alpha1, alpha2, q, sigma, censor_type_vec) {
    .Call(`_ggflexbcr_L_C2_matrix_cpp`, t1, t2, X, beta1, beta2, alpha1, alpha2, q, sigma, censor_type_vec)
}

Observed_ll_cpp <- function(gamma1, gamma2, rho, beta1, beta2, alpha1, alpha2, q, sigma, t1, t2, X, censor_type_vec) {
    .Call(`_ggflexbcr_Observed_ll_cpp`, gamma1, gamma2, rho, beta1, beta2, alpha1, alpha2, q, sigma, t1, t2, X, censor_type_vec)
}

optimize_M2_lc2 <- function(t1, t2, X, Expc_k_given_C_mat, censor_type_vec, init_params, method = "Nelder-Mead") {
    .Call(`_ggflexbcr_optimize_M2_lc2`, t1, t2, X, Expc_k_given_C_mat, censor_type_vec, init_params, method)
}

optimize_M2_lc2_q_fixed <- function(t1, t2, X, Expc_k_given_C_mat, censor_type_vec, q, init_params, method = "Nelder-Mead") {
    .Call(`_ggflexbcr_optimize_M2_lc2_q_fixed`, t1, t2, X, Expc_k_given_C_mat, censor_type_vec, q, init_params, method)
}

optimize_M2_lc2_gamma <- function(t1, t2, X, Expc_k_given_C_mat, censor_type_vec, init_params, method = "Nelder-Mead") {
    .Call(`_ggflexbcr_optimize_M2_lc2_gamma`, t1, t2, X, Expc_k_given_C_mat, censor_type_vec, init_params, method)
}

optimize_M2_lc2_exp <- function(t1, t2, X, Expc_k_given_C_mat, censor_type_vec, init_params, method = "Nelder-Mead") {
    .Call(`_ggflexbcr_optimize_M2_lc2_exp`, t1, t2, X, Expc_k_given_C_mat, censor_type_vec, init_params, method)
}

